<?php

/**
 * Implements hook_permission().
 */
function site_copyright_permission() {
  return array(
    'administer site copyright' => array(
      'title' => t('Administer site copyright'),
      'description' => t('Administer the settings and data for the copyright block.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function site_copyright_menu() {
  $items['admin/config/system/site-copyright'] = array(
    'title' => t('Site Copyright'),
    'description' => 'Configure the site copyright information.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_copyright_configure'),
    'access arguments' => array('administer site copyright'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'site_copyright.admin.inc',
    'file path' => drupal_get_path('module', 'site_copyright'),
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function site_copyright_theme() {
  return array(
    'site_copyright' => array(
      // Specify variables you'll be using in the template.
      'variables' => array(
        // NULL is correct. Values set here are stored in Theme Registry.
        'owner' => NULL,
        'start' => NULL,
        'end' => NULL,
        'phone' => NULL,
        'address' => NULL,
      ),
      // Use a template file called site-copyright.tpl.php.
      'template' => 'templates/site_copyright',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function site_copyright_block_info() {

  $blocks['site_copyright'] = array(
    'info' => t('Site Copyright'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function site_copyright_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'site_copyright':
      // We don't want the block to have a title.
      $block['subject'] = '<none>';
      // Using callback function that returns renderable array. We use a callback
      // function so that we can try to cache the data for faster block rendering.
      $block['content'] = site_copyright_block_content();
      break;
  }

  return $block;
}

/**
 * Callback function to get the renderable array of data for the site copyright block.
 */
function site_copyright_block_content() {
  $content = &drupal_static(__FUNCTION__);

  if (!isset($content)) {
    if ($cache = cache_get('site_copyright_block_content')) {
      $content = $cache->data;
    }
    else {
      $content = array(
        // Specify the theme function to use.
        '#theme' => 'site_copyright',
        // Provide variable values as specified in hook_theme.
        '#copyright' => check_plain(variable_get('site_copyright_owner', 'Company Name')),
        '#copyright_start' => check_plain(variable_get('site_copyright_start', '1885')),
        '#copyright_end' => format_date(time(), 'custom' , 'Y'),
        '#phone' => check_plain(variable_get('site_copyright_phone', '555-867-5309')),
        '#address' => check_plain(variable_get('site_copyright_address', '123 Main St. North Pole')),
      );
      cache_set('site_copyright_block_content', $content, 'cache');
    }
  }

  return $content;
}