<?php

/**
 * Implements hook_menu().
 */
function site_copyright_menu() {
  $items['admin/config/system/site_copyright'] = array(
    'title' => t('Site Copyright'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_copyright_configure'),
    // Use the default/standard site configuration permission.
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'site_copyright.admin.inc',
    'file path' => drupal_get_path('module', 'site_copyright'),
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function site_copyright_theme() {
  return array(
    'site_copyright' => array(
      // Specify variables you'll be using in the template
      'variables' => array(
        // NULL is correct. Values set here are stored in Theme Registry.
        'copyright' => NULL,
        'copyright_start' => NULL,
        'copyright_end' => NULL,
        'phone' => NULL,
        'address' => NULL,
      ),
      // Use a template file called site_copyright.tpl.php
      'template' => 'templates/site_copyright',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function site_copyright_block_info() {
  $blocks['site_copyright'] = array(
    'info' => t('Site Copyright'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function site_copyright_block_view($delta = '') {
  $block = array();

  // Depending on the specified delta return the correct block content.
  // Note: This switch is not required if you have only one block, you can
  // simply return the the block array
  switch ($delta) {
    case 'site_copyright':
      // We don't want the block to have a title.
      $block['subject'] = '<none>';
      // Using a Renderable Array rather than a HTML-returning callback function.
      $block['content'] = array(
        // Specify the theme function to use.
        '#theme' => 'site_copyright',
        // Provide variable values as specified in hook_theme.
        '#copyright' => check_plain(variable_get('site_copyright_copyright', 'Company Name')),
        '#copyright_start' => check_plain(variable_get('site_copyright_copyright_start', '1885')),
        '#copyright_end' => format_date(time(), 'custom' , 'Y'),
        '#phone' => check_plain(variable_get('site_copyright_phone', '555-867-5309')),
        '#address' => check_plain(variable_get('site_copyright_address', '123 Main St. North Pole')),
      );
      break;
  }
  return $block;
}